### ISSUE TITLE
android客户端连接就停止运行

### ISSUE THREAD

**Issue by ghost** [NNdroid/GoFly-Android#1]
客户端是最新版，Android14系统，点连接就停止运行
![c49abe19b2e1ccb6c7f1dec275372539](https://github.com/NNdroid/GoFly-Android/assets/138294823/90185479-2d70-42da-9047-d12584fb78ae)

**Comment by NNdroid** [comment]
Please submit detailed configuration, including server configuration, client configuration, and version number information. Please replace key information with *, but make sure the configuration is consistent.

**Comment by NNdroid** [comment]
If possible, please turn on verbose in the client settings in order to display detailed debugging information, and then logcat to view the output log
